### ISSUE TITLE
[Bug Report]: Offline Selling

### ISSUE THREAD

**Issue by Nachtmaken** [Crazy-Crew/CrazyAuctions#151]
### Spark link

https://spark.lucko.me/u3vCfj9VEL

### Server Version

1.19.3

### Server Platform

Purpur

### Describe the bug

When players have items listed on the auction house and they're offline the buyer gets charged for the item but the seller doesn't receive the money.

### Steps to reproduce

1. List an item.
2. Log off from the server
3. Another online player buys an item
4. When back on the server balance is the same as when you've just logged off.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
Closed due to pending re-write
