### ISSUE TITLE
[Bug Report]: Can't build CrazyAuctions with gradle

### ISSUE THREAD

**Issue by Sliman4** [Crazy-Crew/CrazyAuctions#152]
### Server Version

1.8.8

### Server Platform

Spigot

### Describe the bug

1. In README.md it says that you should run `./gradlew shadowJar`, but there's not `gradlew` or `gradlew.bat` files.
2. When `gradle build` (with my version of gradle) it says:
```
[~/IdeaProjects/CrazyAuctions] gradle build

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':crazyauctions-api:compileJava'.
> Could not resolve all dependencies for configuration ':crazyauctions-api:compileClasspath'.
  The project declares repositories, effectively ignoring the repositories you have declared in the settings.
  You can figure out how project repositories are declared by configuring your build to fail on project repositories.
  See https://docs.gradle.org/8.0.2/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories for details.
   > Could not find us.crazycrew.crazycore:crazycore-api:1.1.0.0.
     Searched in the following locations:
       - https://repo.triumphteam.dev/snapshots/us/crazycrew/crazycore/crazycore-api/1.1.0.0/crazycore-api-1.1.0.0.pom
       - https://repo.crazycrew.us/libraries/us/crazycrew/crazycore/crazycore-api/1.1.0.0/crazycore-api-1.1.0.0.pom
       - https://repo.crazycrew.us/plugins/us/crazycrew/crazycore/crazycore-api/1.1.0.0/crazycore-api-1.1.0.0.pom
       - https://libraries.minecraft.net/us/crazycrew/crazycore/crazycore-api/1.1.0.0/crazycore-api-1.1.0.0.pom
       - https://jitpack.io/us/crazycrew/crazycore/crazycore-api/1.1.0.0/crazycore-api-1.1.0.0.pom
       - https://repo.maven.apache.org/maven2/us/crazycrew/crazycore/crazycore-api/1.1.0.0/crazycore-api-1.1.0.0.pom
     Required by:
         project :crazyauctions-api
```
3. When I install the latest CrazyCore locally and add mavenLocal() repository, it can't find some classes, it's probably a different version with breaking changes, but I'm too lazy to find the necessary commit if there's no github releases or tags. I think it should be in some maven repo

### Steps to reproduce

gradle build

### Additional context

Building the latest commit (ef7c6f0041a5f77eff64dfe81f7af94814dd37e0)

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by RyderBelserion** [comment]
CrazyAuctions is not ready for you to build.
