### ISSUE TITLE
[Bug Report]: enchanted leather armor is in the wrong category

### ISSUE THREAD

**Issue by Draghonir** [Crazy-Crew/CrazyAuctions#156]
### Server Version

1.19.3

### Server Platform

Spigot

### Describe the bug

Hello! I noticed a bug in the CrazyAuctions plugin where enchanted leather armor is in the wrong category. Instead of being in the "armor" category, it's in the "other" category.

First picture is other

<img width="344" alt="rgd" src="https://user-images.githubusercontent.com/107469643/236618827-3439f47b-f1f0-4115-a709-1919e5dfcd95.png">
<img width="346" alt="Capture d’écran 2023-05-06 123159" src="https://user-images.githubusercontent.com/107469643/236618897-168920bd-af75-4950-b030-8ab867dbcb9d.png">

### Steps to reproduce

/ah sell

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [x] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
Closed due to pending re-write
