### ISSUE TITLE
[Bug Report]: CrazyAuctions x EcoEnchants

### ISSUE THREAD

**Issue by Jenkurd1s** [Crazy-Crew/CrazyAuctions#170]
### Server Version

1.20.2

### Server Platform

Paper

### Describe the bug

I have encountered an issue with the CrazyAuctions plugin in conjunction with EcoEnchants. When I list an item with custom enchantments on the auction and then reload the server, the enchantments are removed, even though they were previously saved in the data.yml file under the ENCHANTMENTS section before restart. After restarting, the custom enchantments disappear from the ENCHANTMENTS section, only the vanilla ones remain.

I expected the enchantments to persist after server reload, but they are not being retained. I would appreciate it if you could investigate this issue and suggest a solution.

### Crate Type

None

### Steps to reproduce

1. Installed CrazyAuctions and EcoEnchants on the server.
2. Listed an item with custom enchantments on the auction using CrazyAuctions.
3. Reloaded the server.
4. Noticed that the enchantments disappeared from the item.

### Additional context

Actions I have tried to resolve the issue:
1. Set the plugin loading priority in CrazyAuctions settings as soft-depend.
2. Increased the duration for which items stay on the auction to 90 days.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [ ] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
Fixed in newer versions of CrazyAuctions
