### ISSUE TITLE
[Feature Request]: Hex Color support on the items like Next Page, Your items, Expired items ect... (they don't work right now you cannot click on it to go to the GUI)

### ISSUE THREAD

**Issue by frvzty** [Crazy-Crew/CrazyAuctions#172]
### Describe the feature

Add Hex Color support for the clickable items like next page.

**Comment by ryderbelserion** [comment]
![image](https://github.com/Crazy-Crew/CrazyAuctions/assets/52214219/dc7f6c68-8918-4c62-8457-afa2cedfd50c)

**Comment by ryderbelserion** [comment]
I would say make a bug report but it's not a bug, it's just a limitation of checking display names.

The code handling the menus would have to be completely changed and I don't want to do that right now.

**Comment by ryderbelserion** [comment]
Fixed
