### ISSUE TITLE
Broadcast a message when an item is listed or bought.

### ISSUE THREAD

**Issue by Plexi09** [Crazy-Crew/CrazyAuctions#181]
### Describe the feature

It would be nice to be able broadcast a message when an item is listed or bought. For example, if i buy/sell 64x oak planks, the plugin should broadcast "Plexi09 has purchased/listed 64x oak planks for 1 000$ in the auction house!"

**Comment by Plexi09** [comment]
A discord webhook that does the same would be cool to.

**Comment by ryderbelserion** [comment]
You'll just be able to run commands as well so you can use any plugin that hooks to Discord like DiscordSRV
