### ISSUE TITLE
confirm and cancel cannot be used with hex

### ISSUE THREAD

**Issue by TofaDev** [Crazy-Crew/CrazyAuctions#183]
### Plugin Version

1.4.2

### Server Version

1.20.6

### Server Platform

Paper

### Describe the bug

when you try to specify a hex color in this place:
```

      Confirm: #The Confirm Buttons.
        Item: 'LIME_STAINED_GLASS_PANE'
        Name: '&aConfirm'
      Cancel: #The Cancel Buttons.
        Item: 'RED_STAINED_GLASS_PANE'
        Name: '&cCancel'
```

the buttons in the menu stop working

### Steps to reproduce

1. edit confirm and/or cancel buttons who are responsible for the text on the buttons when agreeing or refusing a purchase
2. restart server
3. try to press the button, nothing's going to happen.

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
Fixed
